# https://taskfile.dev
version: '3'

tasks:
  default:
    desc: "List all tasks"
    cmds:
      - task -a

  linter:
    desc: "Run linter"
    cmds:
      - go generate ./...
      - golangci-lint run

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot

  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --skip validate

    